import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Route, Routes } from 'react-router-dom';
import { StartPage, ProfilePage, SignupInfoPage, ChooseRolePage, ChangeRolePage, BandRegistrationPage, } from '@/pages/user';
import { FanDashboardPage, TicketHistoryPage, SearchPerformancePage, PerformanceDetailPage, } from '@/pages/fan';
import { BandDashboardPage, SearchPlacePage, PlaceFilterPage, PlaceDetailPage, RoomReservationPage, MyPerformancePage, PerformanceCreatePage, } from '@/pages/band';
import { CreatePlacePage, CreateRoomPage, MySpacePage, RoomPage, SpaceOwnerDashboardPage, ReservationsPage, FixPlacePage, } from '@/pages/spaceOwner';
export default function Router() {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(StartPage, {}) }), _jsx(Route, { path: "/role", element: _jsx(ChooseRolePage, {}) }), _jsx(Route, { path: "/role/change", element: _jsx(ChangeRolePage, {}) }), _jsx(Route, { path: "/nickname", element: _jsx(SignupInfoPage, {}) }), _jsx(Route, { path: "/bandname", element: _jsx(SignupInfoPage, {}) }), _jsx(Route, { path: "/register/band/name", element: _jsx(BandRegistrationPage, {}) }), _jsx(Route, { path: "/fan/dashboard", element: _jsx(FanDashboardPage, {}) }), _jsx(Route, { path: "/fan/performances", element: _jsx(SearchPerformancePage, {}) }), _jsx(Route, { path: "/fan/performances/:performanceId", element: _jsx(PerformanceDetailPage, {}) }), _jsx(Route, { path: "/fan/tickets", element: _jsx(TicketHistoryPage, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/band/dashboard", element: _jsx(BandDashboardPage, {}) }), _jsx(Route, { path: "/band/place", element: _jsx(SearchPlacePage, {}) }), _jsx(Route, { path: "/band/place/filter", element: _jsx(PlaceFilterPage, {}) }), _jsx(Route, { path: "/band/place/:placeId", element: _jsx(PlaceDetailPage, {}) }), _jsx(Route, { path: "/band/place/:placeId/room/:roomId/reserve", element: _jsx(RoomReservationPage, {}) }), _jsx(Route, { path: "/band/performance", element: _jsx(MyPerformancePage, {}) }), _jsx(Route, { path: "/band/performance/create", element: _jsx(PerformanceCreatePage, {}) }), _jsx(Route, { path: "/spaceOwner/dashboard", element: _jsx(SpaceOwnerDashboardPage, {}) }), _jsx(Route, { path: "/spaceOwner/space", element: _jsx(MySpacePage, {}) }), _jsx(Route, { path: "/spaceOwner/space/room/:roomId", element: _jsx(RoomPage, {}) }), _jsx(Route, { path: "/spaceOwner/space/create", element: _jsx(CreatePlacePage, {}) }), _jsx(Route, { path: "/spaceOwner/space/create/room", element: _jsx(CreateRoomPage, {}) }), _jsx(Route, { path: "/spaceOwner/reservations", element: _jsx(ReservationsPage, {}) }), _jsx(Route, { path: "/spaceOwner/space/fix", element: _jsx(FixPlacePage, {}) })] }));
}
